name: release-please-main

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.5
        id: release-please
        with:
          release-type: go
          package-name: tools
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github
